# Generated by Django 5.2.8 on 2025-11-14 19:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('defect_percentage', models.FloatField(verbose_name='Процент брака')),
            ],
            options={
                'verbose_name': 'Тип материала',
                'verbose_name_plural': 'Типы материалов',
            },
        ),
        migrations.CreateModel(
            name='PartnerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип партнера',
                'verbose_name_plural': 'Типы партнеров',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('coefficient', models.FloatField(verbose_name='Коэффициент типа продукции')),
            ],
            options={
                'verbose_name': 'Тип продукции',
                'verbose_name_plural': 'Типы продукции',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('stock', models.IntegerField(verbose_name='Остатки')),
                ('min_stock', models.IntegerField(verbose_name='Минимальный остаток')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.materialtype', verbose_name='Тип материала')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование компании')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг')),
                ('address', models.TextField(verbose_name='Юридический адрес')),
                ('director_name', models.CharField(max_length=255, verbose_name='ФИО директора')),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+79999999999'.", regex='^\\+7\\d{10}$')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('logo', models.ImageField(blank=True, upload_to='partner_logos/', verbose_name='Логотип')),
                ('partner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partnertype', verbose_name='Тип партнера')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('min_partner_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная стоимость для партнера')),
                ('package_length', models.FloatField(verbose_name='Длина упаковки')),
                ('package_width', models.FloatField(verbose_name='Ширина упаковки')),
                ('package_height', models.FloatField(verbose_name='Высота упаковки')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.producttype', verbose_name='Тип продукции')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
            },
        ),
        migrations.CreateModel(
            name='SalesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('sale_date', models.DateField(verbose_name='Дата продажи')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner', verbose_name='Партнер')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.product', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'История реализации',
                'verbose_name_plural': 'История реализации',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_quantity', models.FloatField(verbose_name='Количество материала')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.material', verbose_name='Материал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.product', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Рецептура',
                'verbose_name_plural': 'Рецептура',
                'unique_together': {('product', 'material')},
            },
        ),
    ]
